### ISSUE TITLE
BitBar 1.5 beta 1 causes high CPU load and energy drain

### ISSUE THREAD

**Issue by di5ko** [matryer/bitbar#209]
Started using BitBar (1.5 beta 1) today and really loving its potential. I have 3 plugin scripts: Spotify, `df` and some simple `curl` output script.

I've noticed my Macbook getting significantly slower since BitBar is running, seemingly caused by high CPU time (constantly between 25%-35%) which in turn drains energy.

![screen shot 2016-02-09 at 19 50 20](https://cloud.githubusercontent.com/assets/3500071/12927146/e05c1e46-cf66-11e5-9b73-c0749b6768c3.png)

![screen shot 2016-02-09 at 19 50 33](https://cloud.githubusercontent.com/assets/3500071/12927150/e611cf48-cf66-11e5-8874-ca658ce70c4e.png)

![screen shot 2016-02-09 at 19 51 26](https://cloud.githubusercontent.com/assets/3500071/12927181/096c0c4c-cf67-11e5-851c-8ece6f5e7c28.png)

**Comment by di5ko** [comment]
Switching to v1.4 solved this for me.

**Comment by brandonpittman** [comment]
I haven't seen any issue with this.

**Comment by mm2270** [comment]
I'm running a fairly intensive 'system data reporting' plugin I wrote with the BitBar 1.5 beta and I'm not seeing high CPU usage. I only have the one plugin in BitBar right now, so I wonder if this has something to do with using multiple plugins at once? Have you tried disabling one or two and seeing if the issue goes away? Also, what refresh frequency are the plug-ins set to?

Lastly, I see that the OS is telling you to service your battery as per your screenshot, which means your battery is not functioning correctly. I had this happen on an older MBP and I saw the battery drain rapidly in that condition even when not using any power hungry applications. Just saying.

**Comment by di5ko** [comment]
Refresh rates:

- `curl` script: 5 seconds
- `df` script: 1 minute
- spotify script: 10 seconds

After disabling the Spotify script (which seems to me would take the most resources), the situation did not improve. After removing version 1.5 beta 1 and installing version 1.4, the problems have vanished.

**Comment by eripa** [comment]
I've also seen high CPU load on 1.5 b1, in fact I've been forced to quit Bitbar while on battery to not waste too much time. At first I thought it was related to this issue https://github.com/matryer/bitbar/issues/195, but maybe it's two issues?

**Comment by matryer** [comment]
What plugins were you running?

**Comment by eripa** [comment]
@matryer 
I'm running the following:
```
caffeinate.1h.sh
filewatcher.1m.sh
pomodoro.1s.sh
trello.5s.sh
worldclock.30s.sh
```

- caffeinate.1h.sh doesn't do much and is at 1h
- filewatcher.1m.sh is a custom script, it simply runs "ls" on a folder and changes output based on amount of files in the folder
- pomodoro.1s.sh could probably be causing some issues given it's run every second, however it's not very advanced operations
- worldclock.30s.sh is the standard worldclock plugin, but upped to 30s as I don't need the granularity
- trello.5s.sh is my own custom plugin (don't know if it's worth upstreaming yet), this is probably the most taxing one as I run a couple of curl requests every time to speak to the API, parsing them through the 'jq' utility.

But in general I don't see them being super heavy. My 'Avg. Energy Impact' for bitbar according to OS X is 71.72. :snail: 

Usually restarting bitbar helps solve it briefly, seem to be some kind of leak. I'll try downgrading to 1.4 and see if it helps.

**Comment by di5ko** [comment]
Small note after reading @eripa's report: I've extended the Spotify script also to make `curl` requests to their web API and parse the output through the `jq` utility also.

**Comment by matryer** [comment]
Please try the latest 1.5 release. We think we've fixed some memory leaks.

**Comment by matryer** [comment]
Please try this with v1.5.1 release and let us know.

**Comment by eripa** [comment]
Still experiencing this issue. Seem to be related to either curl or jq in plugins. Those are the ones ranking high on energy consumption according to Activity Monitor

Eric

**Comment by matryer** [comment]
If that’s the case, then I think it’s outside the scope of BitBar? Or do you see something BitBar could do to mitigate it?

**Comment by ksuther** [comment]
Have you tried sampling BitBar to see if anything useful appears in the sample?

**Comment by tabacco** [comment]
Still seeing very high CPU usage on 1.5.1

**Comment by cpenner-va** [comment]
I'm running on v1.6 and I'm also experiencing high cpu-usage and energy drain as well. Currently BitBar is using more power that Google Chrome (with like 20 tabs open), which doesn't make any sense for something just running a few scripts in the background.

I only have two plugins: `pomodoro` and `nowplaying` and I have each of them running at 10s hoping that would decrease the cpu usage (it didn't)...

Anyone have ideas? I suppose I could try 1.4, but if something got messed up between 1.4 and 1.5 we should probably figure it out haha. :D

**Comment by roguePanda** [comment]
I noticed lots of `WindowServer[214]: _CGXUnregisterWindowWithSystemStatusBar: Invalid window (1266)` messages in the Console app while BitBar was running, and they seemed to stop when I quit it. There were also periodic CPU usage spikes for WindowServer, so maybe something in BitBar is forcing a lot of UI calculations.

**Comment by iosdeveloper** [comment]
This should be fixed as well by bfb47b3 and c352e7e.
